version: '3'

services:
  postgresql:
    image: bitnami/postgresql:latest
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=kafka_project
      - POSTGRESQL_USERNAME=postgres      
      - POSTGRESQL_PASSWORD=123

  redis:
    image: bitnami/redis:latest
    volumes:
      - redis_data:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  airflow-scheduler:
    image: bitnami/airflow-scheduler:latest
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_DATABASE_NAME=kafka_project
      - AIRFLOW_DATABASE_USERNAME=postgres
      - AIRFLOW_DATABASE_PASSWORD=123
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - ./dataset:/opt/bitnami/dataset
      - ./src/script:/opt/bitnami/script
      - airflow_scheduler_data:/bitnami
      - ./src/airflow/dags:/opt/bitnami/airflow/dags
      - ./src/airflow/plugins:/opt/bitnami/airflow/plugins

  airflow-worker:
    image: bitnami/airflow-worker:latest
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=kafka_project
      - AIRFLOW_DATABASE_USERNAME=postgres
      - AIRFLOW_DATABASE_PASSWORD=123
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - ./dataset:/opt/bitnami/dataset
      - ./src/script:/opt/bitnami/script
      - airflow_worker_data:/bitnami
      - ./src/airflow/dags:/opt/bitnami/airflow/dags
      - ./src/airflow/plugins:/opt/bitnami/airflow/plugins

  airflow:
    image: bitnami/airflow:latest
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_DATABASE_NAME=kafka_project
      - AIRFLOW_DATABASE_USERNAME=postgres
      - AIRFLOW_DATABASE_PASSWORD=123
      - AIRFLOW_USERNAME=user
      - AIRFLOW_PASSWORD=password
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
    ports:
      - '8080:8080'
    volumes:
      - ./dataset:/opt/bitnami/dataset
      - ./src/script:/opt/bitnami/script
      - ./src/airflow/dags:/opt/bitnami/airflow/dags
      - ./src/airflow/plugins:/opt/bitnami/airflow/plugins

volumes:
  airflow_scheduler_data:
    driver: local
  airflow_worker_data:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local
